version: '3.7'

services:

  db.merchantcode:
    image: mariadb:10.3.11
    container_name: db.merchantcode
    ports:
      - 3306
    restart: always
    env_file:
      - ../.env.local

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - transport.host=localhost
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

volumes:
  esdata1:
    driver: local
